version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Checking Node...
      - node -v
      - npm -v
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build step"

  post_build:
    commands:
      - echo Build completed